# Julia Basics: a short introduction through linear algebra

An excellent introduction to Julia can be found in the book [_Erik Engheim, Julia as a second language, Manning Ed._ ](https://www.manning.com/books/julia-as-a-second-language). These book targets people having already some skill with a different language but is an easy read. It is not focused on scientific computing but rather on the basics constructs and  features of the language. 

In this course we will make intensive use of Jupyter notebooks. In order to work with such objects we suggest (but feel free to do otherwise) to:
- [install Julia](https://julialang.org/downloads/)
- install an IDE (I'll use VSCode: a rather fine and free Microsoft product).
- install the Julia extension for VSCode
- install the package IJulia (system wide or in an environment)

With this should be now able to visualize and edit notebooks locally on your laptop.


For this notebook we will need tha Julia package [LinearAlgebra](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/) installed.

In [4]:
#Pkg is the package manager for Julia, and we use it to activate the current project environment.
using Pkg
# Activate the project environment located in the parent directory.
Pkg.activate("..")
using LinearAlgebra

  Activating project at `~/Library/CloudStorage/OneDrive-UniversitàdegliStudidiMilano/Work/Workspace/Unimi/Corsi/TN_Ulm/Materiale_dispense/TN_Notebooks`


If you are not familiar with environments, [this](https://pkgdocs.julialang.org/v1/environments/) is a good read.

## Arrays and matrices

An array of complex values in double precision is created as:

In [5]:
# Create a zero array of complex numbers with 3 elements
cArrZero = zeros(ComplexF64, 3)
# Create a array of complex numbers with 3 elements
cArr = ComplexF64[1+2im, 3+4im, 5+6im]

3-element Vector{ComplexF64}:
 1.0 + 2.0im
 3.0 + 4.0im
 5.0 + 6.0im

In [6]:
cArrZero


3-element Vector{ComplexF64}:
 0.0 + 0.0im
 0.0 + 0.0im
 0.0 + 0.0im

A complex valued matrix can be created as:

In [7]:
# Create a zero matrix of complex numbers with 2 rows and 2 columns
cMatZero = zeros(ComplexF64, 2, 2)
# Create a matrix of complex numbers with 2 rows and 2 columns
cMat = ComplexF64[1+2im 3+4im; 5+6im 7+8im]

2×2 Matrix{ComplexF64}:
 1.0+2.0im  3.0+4.0im
 5.0+6.0im  7.0+8.0im

## Some operations

The norm of the array can be computed as

### Product by a scalar

In [8]:
α = 2.0 + 3.0im

2.0 + 3.0im

In [9]:
cArr

3-element Vector{ComplexF64}:
 1.0 + 2.0im
 3.0 + 4.0im
 5.0 + 6.0im

In [10]:
α * cArr

3-element Vector{ComplexF64}:
 -4.0 + 7.0im
 -6.0 + 17.0im
 -8.0 + 27.0im

### Scalar product

In [11]:
cArr2 = ComplexF64[1,2,3]

3-element Vector{ComplexF64}:
 1.0 + 0.0im
 2.0 + 0.0im
 3.0 + 0.0im

In [12]:
cArr' * cArr2

22.0 - 28.0im

Mind the math!

In [13]:
#This is perfectly correct, but it is not the inner product of cArr and cArr2
cArr * cArr2'

3×3 Matrix{ComplexF64}:
 1.0+2.0im   2.0+4.0im    3.0+6.0im
 3.0+4.0im   6.0+8.0im    9.0+12.0im
 5.0+6.0im  10.0+12.0im  15.0+18.0im

...and don't try

In [14]:
cArr * cArr2

MethodError: MethodError: no method matching *(::Vector{ComplexF64}, ::Vector{ComplexF64})
The function `*` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...)
   @ Base operators.jl:596
  *(!Matched::LinearAlgebra.AbstractRotation, ::AbstractVector)
   @ LinearAlgebra ~/.julia/juliaup/julia-1.11.7+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/givens.jl:12
  *(!Matched::Adjoint{<:Number, <:AbstractVector}, ::AbstractVector{<:Number})
   @ LinearAlgebra ~/.julia/juliaup/julia-1.11.7+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/adjtrans.jl:478
  ...


...unless you want the elementwise product, which is done as:

In [15]:
cArr .* cArr2

3-element Vector{ComplexF64}:
  1.0 + 2.0im
  6.0 + 8.0im
 15.0 + 18.0im

### Norm

In [16]:
sqrt(cArr' * cArr)

9.539392014169456 + 0.0im

or

In [17]:
norm(cArr)
# ! norm knows that the result is a real number, so it returns a real number

9.539392014169456

### Trace

The trace of a matrix is computed as:

In [18]:
tr(cMat)

8.0 + 10.0im

which is the same as summing the elements on the diagonal of `cMat`

In [19]:
tr(cMat) == sum(diag(cMat))

true

The trace is a linear operation:

In [20]:
β = 1.0 - 1.0im
γ = 2.0 + 3.0im
cMat2 = ComplexF64[1 2; 3 4]

2×2 Matrix{ComplexF64}:
 1.0+0.0im  2.0+0.0im
 3.0+0.0im  4.0+0.0im

In [21]:
tr(β * cMat + γ * cMat2) == β * tr(cMat) + γ * tr(cMat2)

true

### Eigensystem

Solving the eigensystem of `cMat`: `eigen` returns a couple `(eigenvaluse,eigenvectors)`, with the eigenvectors the columns of a matrix

In [22]:
eigvls,eigvcs = eigen(cMat)

Eigen{ComplexF64, ComplexF64, Matrix{ComplexF64}, Vector{ComplexF64}}
values:
2-element Vector{ComplexF64}:
 -0.8845984302677805 - 0.7323033612130526im
    8.88459843026778 + 10.732303361213052im
vectors:
2×2 Matrix{ComplexF64}:
  0.833134+0.0im        0.389511+0.0355148im
 -0.552635-0.0219453im  0.920337+0.0im

In [23]:
cMat * eigvcs[:,1] ==  eigvcs[:,1]*eigvls[1]

false

In [24]:
≈

isapprox (generic function with 13 methods)

...remember that finite precision is a tricky business...

In [25]:
cMat * eigvcs[:,1] ≈ eigvcs[:,1]*eigvls[1]

true

In [26]:
cMat * eigvcs[:,2] ≈ eigvcs[:,2]*eigvls[2]

true

### Singular Value Decomposition

Singular Value Decomposition (SVD) of a matrix:

In [27]:
uu,ss,vv = svd(cMat)

SVD{ComplexF64, Float64, Matrix{ComplexF64}, Vector{Float64}}
U factor:
2×2 Matrix{ComplexF64}:
  -0.20339-0.318225im   0.693053+0.614038im
 -0.584018-0.718532im  -0.309291-0.216735im
singular values:
2-element Vector{Float64}:
 14.238584272170607
  1.1237072235666075
Vt factor:
2×2 Matrix{ComplexF64}:
 -0.566849+0.0im  -0.823077+0.0350246im
 -0.823822+0.0im   0.566336-0.0240994im

In [28]:
uu * Diagonal(ss) * vv' ≈ cMat

true

### Reshaping

In [29]:
cMat

2×2 Matrix{ComplexF64}:
 1.0+2.0im  3.0+4.0im
 5.0+6.0im  7.0+8.0im

In [30]:
reshape(cMat, 4, 1)

4×1 Matrix{ComplexF64}:
 1.0 + 2.0im
 5.0 + 6.0im
 3.0 + 4.0im
 7.0 + 8.0im

This reveals that Julia is memorizing (i.e. flattening in the memory) matrices in column-major format

In [31]:
reshape(cMat, 1, 4)

1×4 Matrix{ComplexF64}:
 1.0+2.0im  5.0+6.0im  3.0+4.0im  7.0+8.0im

If you want to reshape into an array by concatenating the rows, you first need to provide an different _view_ on the data and then reshape

In [32]:
reshape(PermutedDimsArray(cMat, (2,1)), 4, 1)

4×1 reshape(PermutedDimsArray(::Matrix{ComplexF64}, (2, 1)), 4, 1) with eltype ComplexF64:
 1.0 + 2.0im
 3.0 + 4.0im
 5.0 + 6.0im
 7.0 + 8.0im

## Julia functions

In [33]:
function vecbyRow(M)
    return reshape(PermutedDimsArray(M, (2,1)), length(M), 1)
end

vecbyRow (generic function with 1 method)

In [34]:
vecbyRow(cMat)

4×1 reshape(PermutedDimsArray(::Matrix{ComplexF64}, (2, 1)), 4, 1) with eltype ComplexF64:
 1.0 + 2.0im
 3.0 + 4.0im
 5.0 + 6.0im
 7.0 + 8.0im

In [35]:
function orthonormalize(v::Vector{ComplexF64})
    return v / norm(v)
end

orthonormalize (generic function with 1 method)

In [36]:
norm(orthonormalize(cArr))

1.0

In [37]:
function orthonormalize(v::Vector{Vector{ComplexF64}})
    #Create an empty vector of vectors of complex numbers
    res = Vector{Vector{ComplexF64}}()
    #Check if the input vector is empty
    if(length(v) == 0)
        println("The input vector is empty, returning the empty vector")
        return v
    else
        size = length(v)
        appo = v[1]/norm(v[1])
        for i in 1:size
            push!(res, appo)
            if i < size
                appo = v[i+1] - sum(res[j]' * v[i+1] * res[j] for j in 1:i)
                appo = appo / norm(appo)
            end

        end
        return res
    end
end

orthonormalize (generic function with 2 methods)

In [38]:
basis = orthonormalize([cArr, cArr2])

2-element Vector{Vector{ComplexF64}}:
 [0.10482848367219183 + 0.20965696734438366im, 0.3144854510165755 + 0.4193139346887673im, 0.5241424183609592 + 0.628970902033151im]
 [0.556348640264187 - 0.6847367880174609im, 0.17118419700436543 - 0.17118419700436543im, -0.2139802462554557 + 0.34236839400873im]

This is an example of Julia's multiple dispatch: Julia determines which function to actually invoke by checking the type of the input parameters. This is something similar to function/operator overloading (as in C++) and somehow mitigates the lack of objects...in order to understand the difference you should by familiar with the difference between static and dynamic binding...but it is far beeyond the scope of this course.

### Exercise

- Create a $4 x \times 4$ matrix $A$ of complex numbers with elements:
$$
\begin{cases}
A_{j,j} = 1. \\
A_{j,k} = j^2 + k^2 \;\text{i}\; \text{if } k>j \\
A_{j,K} = A_{k,j}^*\; \text{if } k<j.
\end{cases}
$$
- Determine the eigenvalues and the eigenvectors of $A$ by means of the `eigen` Julia function.
- Check that the eigenvalues/eigenvectors are correct i.e. $A \cdot \vec{e}_k = e_k \vec{e}_k$
- Check that the eigevectors are orthonormal.
- Reshape the matrix into:
  -  a single column ($16 \times 1$ matrix) with stacked columns;
  -  a single row ($1 \times 16$) with the rows of $A$ concatenated.

 